gh-468 Display data decoded
safe-global/safe-ios pull request #494
Opened 2020-08-24 12:59 UTC by MouazAlzahabi

2020-08-24 14:26 UTC, DmitryBespalov requested changes

2020-08-24 14:26 UTC, DmitryBespalov commented on Multisig/Data/Services/Safe Client Gateway Service/SCGModels.swift
> +        return self as? String
`return` can be skipped

2020-08-24 14:26 UTC, DmitryBespalov commented on Multisig/Data/Services/Safe Client Gateway Service/SCGModels.swift
> +        return self as? [DataDecodedParameterValue]
`return` can be removed

2020-08-24 14:26 UTC, DmitryBespalov commented on Multisig/Logic/Models/Transaction/TransactionData.swift
> +    func hash(into hasher: inout Hasher) {
👍

2020-08-24 14:26 UTC, DmitryBespalov commented on Multisig/Logic/Models/Transaction/TransactionData.swift
> +        return lhs.name == rhs.name && lhs.type == rhs.type && lhs.value == rhs.value
`return` can be removed, this thing has another fancy  way of doing, whatever you prefer:

```
(lhs.name, lhs.type, lhs.value)  == (rhs.name, rhs.type, rhs.value)
```

2020-08-24 14:26 UTC, DmitryBespalov commented on Multisig/UI/Transactions/TransactionDetails/ParameterValueView.swift
> +                ForEach((0..<value!.arrayValue!.count)) { index in
we haven't tested this case  of  nested array values yet with  actual transaction

2020-08-24 14:26 UTC, DmitryBespalov commented on Multisig/UI/Transactions/TransactionDetails/TransactionDetailsView.swift
> +            if transaction.dataDecoded != nil {
it  should also check that the type of transaction is custom transaction

2020-08-24 15:57 UTC, sche commented on Multisig/UI/Transactions/TransactionDetails/ParameterValueView.swift
> +        else if stringValue != nil  {
tiny: could you put is on the same line, please?

2020-08-24 15:58 UTC, sche commented on Multisig/UI/Transactions/TransactionDetails/ParameterValueView.swift
> +        guard let value = value else { return "-"}
space after "}"

2020-08-24 15:58 UTC, sche approved these changes

2020-08-25 06:49 UTC, DmitryBespalov approved these changes

2020-08-25 08:21 UTC, sche approved these changes

2020-08-25 09:23 UTC, merged