Gh 504/client gateway integration
safe-global/safe-ios pull request #552
Opened 2020-09-15 10:36 UTC by MouazAlzahabi

2020-09-15 15:03 UTC, sche commented on Multisig/UI/Transactions/TransactionCell/CustomTransactionCellView.swift
> +                Text(transaction.amount + " \(transaction.tokenSymbol)")
why like this?

2020-09-15 15:04 UTC, sche commented on Multisig/UI/Transactions/TransactionCell/SettingsChangeTransactionCell/SettingsChangeTransactionCellView.swift
> +        let setFallbackHandler = transaction.info as? SetFallbackHandlerSettingsChangeTransactionSammaryInfo
Spelling: 'S_u_mmary'

2020-09-15 15:08 UTC, sche commented on Multisig/UI/Transactions/TransactionDetails/TransactionDetailsViewModel.swift
> +                .compactMap { $0 }
is this compactMap needed?

2020-09-15 15:09 UTC, sche commented on Multisig/UI/Transactions/TransactionDetails/TransactionDetailsViewModel.swift
> +            .receive(on: DispatchQueue.global())
tabulation

2020-09-15 15:16 UTC, sche approved these changes

2020-09-16 08:43 UTC, DmitryBespalov requested changes
Big effort! 👍 

Some code duplication in several places and minor changes need to be corrected

2020-09-16 08:43 UTC, DmitryBespalov commented on Multisig/Data/Services/Safe Client Gateway Service/TransactionSummaryListRequest.swift
> +    typealias ResponseType =  Page<TransactionSummary>
extra space after `=`

2020-09-16 08:43 UTC, DmitryBespalov commented on Multisig/UI/Transactions/TransactionDetails/TransactionDetailsViewModel.swift
> +            Just(id)
These two branches are very look-alike, please extract the copy-pasted part into a separate method that would accept a closure parameter that you can execute inside the tryMap

2020-09-16 08:43 UTC, DmitryBespalov commented on Multisig/UI/Transactions/TransactionListViewModel/CreationTransactionViewModel.swift
> +        guard isValid(info: tx.txInfo) else {
could be replaced with one-liner

```
isValid(info: tx.txInfo) ? [CreationTransactionViewModel(tx)] : []
```

The same one-liner could be used in teh CustomTransactionSummaryViewModel

2020-09-16 08:43 UTC, DmitryBespalov commented on Multisig/UI/Transactions/TransactionListViewModel/SettingChangeTransactionViewModel.swift
> +        guard isValid(info: tx.txInfo) else {
here, too, can be just one ternary operator

2020-09-16 08:43 UTC, DmitryBespalov commented on Multisig/UI/Transactions/TransactionListViewModel/TransactionViewModel+Factory.swift
> +        ?? []
the only thing that is different is the input parameter and the viewModels() variant, please remove the copy-pasted duplication by extracting the common part into a separate configurable method

2020-09-16 08:43 UTC, DmitryBespalov commented on Multisig/UI/Transactions/TransactionListViewModel/TransferTransactionViewModel.swift
> +        return [TransferTransactionViewModel(tx)]
here, too, can be replaced by ternary operator

2020-09-16 11:51 UTC, DmitryBespalov approved these changes

2020-09-17 15:14 UTC, DmitryBespalov approved these changes

2020-09-17 15:48 UTC, merged